=== J-D-Rosales/Proyecto-de-200-millas/DataGenerator/schemas-validation/empleados.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Empleados",
  "type": "object",
  "x-dynamodb": {
    "partition_key": "local_id",
    "sort_key": "dni"
  },
  "properties": {
    "local_id": {
      "type": "string"
    },
    "dni": {
      "type": "string"
    },
    "nombre": {
      "type": "string"
    },
    "apellido": {
      "type": "string"
    },
    "role": {
      "type": "string",
      "enum": [
        "Repartidor",
        "Cocinero",
        "Despachador"
      ]
    }
  },
  "required": [
    "local_id",
    "dni",
    "nombre",
    "apellido",
    "role"
  ],
  "additionalProperties": false
}

=== J-D-Rosales/Proyecto-de-200-millas/DataGenerator/example-data/empleados.json
[
  {
    "local_id": "LOCAL-002",
    "dni": "24544907",
    "nombre": "Sofía",
    "apellido": "Ramírez",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "11761968",
    "nombre": "María",
    "apellido": "García",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "97980132",
    "nombre": "Valentina",
    "apellido": "Silva",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "76658496",
    "nombre": "Miguel",
    "apellido": "Torres",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "95212066",
    "nombre": "Camila",
    "apellido": "Rodríguez",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "52952513",
    "nombre": "José",
    "apellido": "Pérez",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "37822287",
    "nombre": "Luis",
    "apellido": "Flores",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "39271094",
    "nombre": "Laura",
    "apellido": "Flores",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "22564176",
    "nombre": "Carlos",
    "apellido": "Pérez",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "26892951",
    "nombre": "Pedro",
    "apellido": "López",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-002",
    "dni": "59438741",
    "nombre": "Ana",
    "apellido": "Sánchez",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "16554254",
    "nombre": "Pedro",
    "apellido": "Sánchez",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "18841952",
    "nombre": "Sofía",
    "apellido": "Castro",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "59868788",
    "nombre": "Diego",
    "apellido": "Sánchez",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-002",
    "dni": "11776695",
    "nombre": "Miguel",
    "apellido": "Morales",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-002",
    "dni": "79403052",
    "nombre": "Valentina",
    "apellido": "Sánchez",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "59906609",
    "nombre": "Luis",
    "apellido": "Silva",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "52417420",
    "nombre": "Valentina",
    "apellido": "Torres",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "84922818",
    "nombre": "Valentina",
    "apellido": "González",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "93884638",
    "nombre": "Sofía",
    "apellido": "Pérez",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "47531331",
    "nombre": "Diego",
    "apellido": "González",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "50239803",
    "nombre": "María",
    "apellido": "Torres",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "95312652",
    "nombre": "Pedro",
    "apellido": "López",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-002",
    "dni": "21170634",
    "nombre": "Pedro",
    "apellido": "Pérez",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-002",
    "dni": "37132174",
    "nombre": "Carmen",
    "apellido": "Morales",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "64825968",
    "nombre": "Pedro",
    "apellido": "Pérez",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "55971185",
    "nombre": "Carmen",
    "apellido": "Pérez",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-002",
    "dni": "62237875",
    "nombre": "Carlos",
    "apellido": "Rodríguez",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "18492370",
    "nombre": "Valentina",
    "apellido": "López",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "70161172",
    "nombre": "María",
    "apellido": "García",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-002",
    "dni": "39816780",
    "nombre": "Juan",
    "apellido": "Ortiz",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-002",
    "dni": "77058567",
    "nombre": "Sofía",
    "apellido": "Sánchez",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "63364442",
    "nombre": "José",
    "apellido": "López",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-002",
    "dni": "56693693",
    "nombre": "Andrés",
    "apellido": "Torres",
    "role": "Despachador"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "39796971",
    "nombre": "Ana",
    "apellido": "Ramírez",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-002",
    "dni": "61743870",
    "nombre": "Camila",
    "apellido": "García",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "11888028",
    "nombre": "Pedro",
    "apellido": "González",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-001",
    "dni": "21998836",
    "nombre": "Diego",
    "apellido": "González",
    "role": "Repartidor"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "76369395",
    "nombre": "Sofía",
    "apellido": "Sánchez",
    "role": "Cocinero"
  },
  {
    "local_id": "LOCAL-003",
    "dni": "84835880",
    "nombre": "Valentina",
    "apellido": "Sánchez",
    "role": "Repartidor"
  }
]
