=== J-D-Rosales/Proyecto-de-200-millas/DataGenerator/schemas-validation/usuarios.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Usuarios",
  "type": "object",
  "x-dynamodb": {
    "partition_key": "correo"
  },
  "properties": {
    "nombre": {
      "type": "string"
    },
    "correo": {
      "type": "string",
      "format": "email"
    },
    "contrasena": {
      "type": "string",
      "minLength": 6
    },
    "role": {
      "type": "string",
      "enum": [
        "Cliente",
        "Gerente",
        "Admin"
      ]
    }
  },
  "required": [
    "nombre",
    "correo",
    "contrasena",
    "role"
  ],
  "additionalProperties": false
}

=== J-D-Rosales/Proyecto-de-200-millas/DataGenerator/example-data/usuarios.json
[
  {
    "nombre": "Administrador General",
    "correo": "admin@200millas.com",
    "contrasena": "admin123",
    "role": "Admin"
  },
  {
    "nombre": "Miguel López",
    "correo": "miguel.lopez@gmail.com",
    "contrasena": "ger_aafed546",
    "role": "Gerente"
  },
  {
    "nombre": "Valentina Sánchez",
    "correo": "valentina.sanchez@hotmail.com",
    "contrasena": "ger_6dc7fd52",
    "role": "Gerente"
  },
  {
    "nombre": "Valentina Fernández",
    "correo": "valentina.fernandez@hotmail.com",
    "contrasena": "ger_8f9b3b88",
    "role": "Gerente"
  },
  {
    "nombre": "Luis Silva",
    "correo": "luis.silva@outlook.com",
    "contrasena": "cli_729ca0b29b",
    "role": "Cliente"
  },
  {
    "nombre": "María Pérez",
    "correo": "maria.perez@gmail.com",
    "contrasena": "cli_7b6a6aacbd",
    "role": "Cliente"
  },
  {
    "nombre": "Ana Torres",
    "correo": "ana.torres@gmail.com",
    "contrasena": "cli_024a43f9a2",
    "role": "Cliente"
  },
  {
    "nombre": "Luis Ramírez",
    "correo": "luis.ramirez@gmail.com",
    "contrasena": "cli_722925c64e",
    "role": "Cliente"
  },
  {
    "nombre": "Camila López",
    "correo": "camila.lopez@hotmail.com",
    "contrasena": "cli_25aef294ed",
    "role": "Cliente"
  },
  {
    "nombre": "Isabel García",
    "correo": "isabel.garcia@hotmail.com",
    "contrasena": "cli_b11fb52f8a",
    "role": "Cliente"
  },
  {
    "nombre": "Camila Pérez",
    "correo": "camila.perez@hotmail.com",
    "contrasena": "cli_aa3bf2a79b",
    "role": "Cliente"
  },
  {
    "nombre": "Carmen Pérez",
    "correo": "carmen.perez@hotmail.com",
    "contrasena": "cli_8b8dcdfde9",
    "role": "Cliente"
  },
  {
    "nombre": "José Ortiz",
    "correo": "jose.ortiz@outlook.com",
    "contrasena": "cli_76642dac18",
    "role": "Cliente"
  },
  {
    "nombre": "Valentina González",
    "correo": "valentina.gonzalez@outlook.com",
    "contrasena": "cli_d1b99c75ff",
    "role": "Cliente"
  },
  {
    "nombre": "Valentina Rodríguez",
    "correo": "valentina.rodriguez@gmail.com",
    "contrasena": "cli_2ed3a59a6a",
    "role": "Cliente"
  },
  {
    "nombre": "Sofía Fernández",
    "correo": "sofia.fernandez@gmail.com",
    "contrasena": "cli_6b71d2c568",
    "role": "Cliente"
  },
  {
    "nombre": "Miguel Castro",
    "correo": "miguel.castro@outlook.com",
    "contrasena": "cli_03544834c2",
    "role": "Cliente"
  },
  {
    "nombre": "Sofía Rodríguez",
    "correo": "sofia.rodriguez@outlook.com",
    "contrasena": "cli_5fa4126aba",
    "role": "Cliente"
  },
  {
    "nombre": "Camila Flores",
    "correo": "camila.flores@outlook.com",
    "contrasena": "cli_07e7e19a9b",
    "role": "Cliente"
  },
  {
    "nombre": "Andrés García",
    "correo": "andres.garcia@gmail.com",
    "contrasena": "cli_68cc4e24e3",
    "role": "Cliente"
  },
  {
    "nombre": "Carlos González",
    "correo": "carlos.gonzalez@gmail.com",
    "contrasena": "cli_7830cc9adc",
    "role": "Cliente"
  },
  {
    "nombre": "Pedro Torres",
    "correo": "pedro.torres@gmail.com",
    "contrasena": "cli_be5f48f6fe",
    "role": "Cliente"
  },
  {
    "nombre": "Pedro López",
    "correo": "pedro.lopez@outlook.com",
    "contrasena": "cli_b6c3efc360",
    "role": "Cliente"
  },
  {
    "nombre": "Juan García",
    "correo": "juan.garcia@outlook.com",
    "contrasena": "cli_ecd84fe9df",
    "role": "Cliente"
  },
  {
    "nombre": "Valentina Martínez",
    "correo": "valentina.martinez@hotmail.com",
    "contrasena": "cli_833222aec4",
    "role": "Cliente"
  },
  {
    "nombre": "Luis Silva",
    "correo": "luis.silva@gmail.com",
    "contrasena": "cli_2fc19a3236",
    "role": "Cliente"
  },
  {
    "nombre": "Luis García",
    "correo": "luis.garcia@gmail.com",
    "contrasena": "cli_68d58a127d",
    "role": "Cliente"
  },
  {
    "nombre": "Carlos Silva",
    "correo": "carlos.silva@gmail.com",
    "contrasena": "cli_a0bc3feb7c",
    "role": "Cliente"
  },
  {
    "nombre": "Ana Castro",
    "correo": "ana.castro@outlook.com",
    "contrasena": "cli_736ef02c6c",
    "role": "Cliente"
  },
  {
    "nombre": "Carmen Ramírez",
    "correo": "carmen.ramirez@outlook.com",
    "contrasena": "cli_31cf300d28",
    "role": "Cliente"
  }
]
